export const SET_RESTAURANT_DATA = 'SET_RESTAURANT_DATA'

export const HOLD_ADDRESS = 'HOLD_ADDRESS'

export const ADD_MENU_ITEM = 'ADD_MENU_ITEM'
export const REMOVE_ITEM = 'REMOVE_ITEM'

export const ADD_ITEM_PRICE = 'ADD_ITEM_PRICE'
export const SUBTRACT_ITEM_PRICE = 'SUBTRACT_ITEM_PRICE'

export const ADD_ITEM = 'ADD_ITEM'

export const REMOVE_ORDER = 'REMOVE_ORDER'
export const SEE_ORDER_HISTORY = 'SEE_ORDER_HISTORY'
 
